### ISSUE TITLE
[가족 생성하기, 글 업로드, 마이페이지] 고해상도 이미지 resize 필요

### ISSUE THREAD

**Issue by boring-km** [familymoments/family-moments-android#84]
### Describe

- 이미지를 업로드 할 때 원본 이미지를 압축하여, 저용량 썸네일용 이미지와 원본 이미지 (이것도 필요 시 최소한의 압축) 2개를 만들어서 업로드하기
- 한 번에 여러 이미지를 보여주는 화면은 썸네일용 이미지 사용
- 이미지를 크게 보는 화면에서만 원본 이미지 사용

### Todo

- [ ] 1. 이미지 업로드 API 확인
- [ ] 2. 이미지 업로드 시, 모든 이미지마다 썸네일과 원본 이미지 2개를 업로드 할 수 있도록 API 수정 요청
- [ ] 3. 이미지 압축 기능 개발
- [ ] 4. 수정된 API 적용
- [ ] 5. 이미지 조회하는 화면들 썸네일 URL로 조회할 수 있도록 변경

## 서버 API 변경이 요구되는 일이라 조심스럽지만 필요한 작업입니다... ㅠㅠ

모바일에서 촬영한 사진 중 용량이 큰 이미지는 여러개의 사진을 보여주는 화면에서 이미지 Size가 작은 썸네일용 이미지를 사용해야 합니다.
1. 원본 사이즈의 이미지를 동시에 여러 개를 다운로드 받아서 그리게 되면 화면 상에서 이미지의 Render 속도는 느리다. -> 특히 가족 앨범 화면의 경우 인피니티 스크롤로 내리면서 로딩하는 속도가 느림을 체감할 수 있을 듯.
2. 서버에서 다운로드 하는 양이 커짐에 따라 서버 비용 또한 크게 나올 수 있다.

**Comment by boring-km** [comment]
서버에서 이미지 썸네일 제작해주는 것으로 변경되어서 해결
